### ISSUE TITLE
Bigint: Failed to load bindings

### ISSUE THREAD

**Issue by mikacmn** [RaydiumGOD/Solana-Token-Creation#2]
Getting this error when running it:

C:\Users\Administrator\Desktop\Solana-Token-Creation-main>node ./main.js
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error
    at pRetry__default.default.retries (C:\Users\Administrator\Desktop\Solana-Token-Creation-main\node_modules\nft.storage\dist\src\lib.cjs:242:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (C:\Users\Administrator\Desktop\Solana-Token-Creation-main\node_modules\p-retry\index.js:50:12)

Node.js v20.12.2

Can't seem to find a fix
Did everything like in documentation

**Comment by Armeliot** [comment]
Same

**Comment by tundachef** [comment]
Basically, I put the image and metadata.json files on my server/domain.

`const fs = require('fs');
const {createToken} = require('./src/create_token.js')
const { NFTStorage, Blob,File} = require ('nft.storage')


const {
    NFT_STORAGE_TOKEN,
    revokeMintBool,
    revokeFreezeBool,
    tokenInfo,
    metaDataforToken
} = require('./config.js')




async function main() {

    // uploadMetaData
    const metadata_url = await uploadMetaData()
    if (!metadata_url){
        console.log("Metadata failed")
        return;
    }
    tokenInfo.metadata = metadata_url

    // Create token
    console.log("Creating Token...")
    const mintAddress = await createToken(tokenInfo, revokeMintBool, revokeFreezeBool)
    console.log(`Mint Link: https://solscan.io/token/${mintAddress.toString()}`)


}




async function uploadMetaData() {
    // console.log('cow')
    const imageUrl = `https://domain.mine/image.png`
    metaDataforToken.image = imageUrl


    // // store as a json file
    // run this to generate metadata.json
    // const jsonString = JSON.stringify(metaDataforToken, null, 2);
    // const file = new File([jsonString], "metadata.json", {type: "application/json"});
    // try {
    //     const filePath = './metadata.json';
    //     fs.writeFileSync(filePath, jsonString);
    //     console.log('File saved successfully:', filePath);
    // } catch (error) {
    //     console.error('Error saving file:', error);
    // }

    const metadata_url = `https://domain.mine/metadata.json`
    console.log('Metadata URI: ', metadata_url)

    
    return metadata_url

  }

  main()```

**Comment by SavyMe** [comment]
Did it cost any Sol to create the new token? I am new to this.

**Comment by tundachef** [comment]
> @tundachef Did it cost any Sol to create the new token? I am new to this.

Of course it did, but about 3 USD worth of solana, including revoke freeze authority and mint authority

**Comment by SavyMe** [comment]
@tundachef thanks mate. But if it's creating new wallets on the fly, how may one add some Sol to it?

```ts
  const mintKeypair = Keypair.generate();
  const myPublicKey = myKeyPair.publicKey;
```

**Comment by tundachef** [comment]
No it only uses your public key follow the repository instructions

**Comment by SavyMe** [comment]
I got it right after I asked you. Thanks a million! 👍
